### ISSUE TITLE
Add Debug instance for MatchOptions

### ISSUE THREAD

**Issue by ndmitchell** [rust-lang/glob#100]
It's pretty useful when debugging to have a Debug instance available. I have a record in my project, for which I'd like Debug, but it's slightly complicated because it embeds a MatchOptions in it. Would it be possible to derive Debug for MatchOptions?

**Comment by JohnTitor** [comment]
That has been added by https://github.com/rust-lang/glob/pull/91, we have to cut a new release including it.

**Comment by JohnTitor** [comment]
0.3.1 is now released, closing as done.
