### ISSUE TITLE
Dead project ?

### ISSUE THREAD

**Issue by corebreaker** [rust-lang/glob#109]
Last merge more than one year. What is the status of this project. Could someone follow up this project ?

**Comment by Esc4iCEscEsc** [comment]
Dead? Did you try the code? It works perfectly fine for what it's supposed to do, unless you have encountered some issue that hasn't been fixed? I'd call it `Done`, not `Dead`.

**Comment by corebreaker** [comment]
Ok, it was just a question cause there is issues and no PR for ages.

**Comment by EvanCarroll** [comment]
It doesn't look good to have 33 open issues and open PRs on a "Done" project.

**Comment by rusty-snake** [comment]
To extend the 33 open issues and open PR, there are also [unreleased changes](https://github.com/rust-lang-nursery/glob/compare/0.3.0...master) and a "Done" project should be at 1.0.0 and not 0.3.0.

**Comment by JohnTitor** [comment]
The [crate maintainers team](https://www.rust-lang.org/governance/teams/library#Crate%20maintainers) now maintains this crate, so the situation should/will be resolved :)
