### ISSUE TITLE
Can you please cut a release of HEAD?

### ISSUE THREAD

**Issue by schneems** [rust-lang/glob#117]
Hello! Thank you for your project. Can you please cut a release? https://github.com/rust-lang/glob/compare/0.3.0...master

I want to debug glob matching but 0.3.0 does not implement `Debug` on `Paths` while the main branch currently does. Originally I went to submit a PR to add a derive for `Debug` when I saw it was already there.

I understand I can use GitHub, but cutting a release might prevent others from going through the same journey. If you're looking for help releasing, I'll offer to help. I'm not well-known in Rust but have credentials in Ruby.

**Comment by JohnTitor** [comment]
Sorry for the delay! v0.3.1 is now out: https://crates.io/crates/glob/0.3.1

**Comment by schneems** [comment]
Thank you!
