### ISSUE TITLE
{a/**} returns error

### ISSUE THREAD

**Issue by samdenty** [rust-lang/glob#123]
```rs
use glob::{MatchOptions, Pattern};

fn main() {
    Pattern::new("{a/**}").unwrap();
}
```

PatternError { pos: 5, msg: "recursive wildcards must form a single path component" }'

**Comment by JohnTitor** [comment]
Note that this crate is for file paths. The error happens because `}` is not a separator.

**Comment by samdenty** [comment]
The glob I was actually using was `{a,a/**}` to capture `a` and any subfile of a

**Comment by JohnTitor** [comment]
The curly braces pattern isn't supported by this crate unfortunately, https://crates.io/crates/globset is a good alternative here if you need it immediately.

**Comment by d3lm** [comment]
Is this something you'd wanna support for this crate?

**Comment by JohnTitor** [comment]
Sorry, I'm fairly new here and don't think I completely understand this crate's policy, so I cannot answer it right now.
Anyway, the question itself should be resolved now and there's already an [open issue to ask the support for it](https://github.com/rust-lang/glob/issues/2), let's continue the discussion there.
