### ISSUE TITLE
The pattern `**` does not match files

### ISSUE THREAD

**Issue by tae-soo-kim** [rust-lang/glob#129]
The pattern `"/usr/bin/**"` does not match files in dir `/usr/bin`. Other tools will do. There needs to be better documentation about this `**` pattern.

**Comment by JohnTitor** [comment]
[It's already documented](https://docs.rs/glob/latest/glob/struct.Pattern.html):
```
** matches the current directory and arbitrary subdirectories. This sequence must form a single path component, so both **a and b** are invalid and will result in an error. A sequence of more than two consecutive * characters is also invalid.
```

Use `**/*` to match files.
