### ISSUE TITLE
Suggests to publish a new version to fix `windows verbatim disk path prefix` issue.

### ISSUE THREAD

**Issue by wangziling** [rust-lang/glob#145]
OS: windows11
rustc: rustc 1.78.0 (9b00956e5 2024-04-29)
cargo: cargo 1.78.0 (54d8815d0 2024-03-26)

---

I had noticed that `glob="=0.3.1"` crate cannot correctly fetch with the partern `r"\\?\E:\Codes\Source\cargo\crates\*"`.
![image](https://github.com/rust-lang/glob/assets/24818903/1554396f-d221-42f3-a6f8-9c02ce0f5b9e)

The issue-recur steps：

1. Pull down the source code of the `rust-lang/cargo` repo into `E:\Codes\Source\cargo` directory.
2. Using the crate `glob="=0.3.1"` to fetch the pattern `r"\\?\E:\Codes\Source\cargo\crates\*"`.

It fails due to the `0.3.1` ver `glob` cannot correctly handle on `windows verbatim DISK prefix`.

---

After I pulled down this repo's sourcecode and did some customize fixes on myself(worked well), finally, I found the source code do fixed this issue in the past year.
![image](https://github.com/rust-lang/glob/assets/24818903/75a40569-92e5-4235-a0b1-cea53999de95)

The result with the latest source code:
![image](https://github.com/rust-lang/glob/assets/24818903/3bfd8951-fb69-4f40-9d50-d087126250c0)

So I suggest that maybe the team should publish a new version with the latest codes, 'cause the `glob="=0.3.1"` is outdated.

**Comment by emabee** [comment]
Is a new glob version with this fix planned already? Is there some workaround for the time being?

**Comment by wangziling** [comment]
> Is a new glob version with this fix planned already? Is there some workaround for the time being?

Hi~ I have closed this issue.

I thought that maybe we need to do some extra logic to correct the UNC paths before using `glob` crate.

I had fixed the issue that I met: https://github.com/regexident/cargo-modules/pull/292

Using the [dunce](https://crates.io/crates/dunce) crate, refer to here: https://github.com/rolldown/rolldown/blob/main/crates/rolldown_testing/src/fixture.rs#L15
