### ISSUE TITLE
"**" pattern on Windows.

### ISSUE THREAD

**Issue by sp0** [rust-lang/glob#40]
I was constructing a pattern like so: 
```
let pattern = path.join("**/*.rs");
```
Which works fine on linux. On windows I get an error:
```
Pattern syntax error near position 3: recursive wildcards must form a single path component
```
This is because the pattern is expected to be something like ```src/**/*.rs```. However on windows, it would be ```src\**/*.rs```. Is this a bug, or am I constructing a pattern which should be considered invalid?

**Comment by blaenk** [comment]
Thanks for reporting this. #41 should fix this.
