### ISSUE TITLE
glob("foo/**") and glob("foo/**/**") do not yield all pathes which are expected.

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/glob#52]
Here is my layout:

```
/tmp/store/
├── diary
│   └── testdiary
│       └── 2016
│           └── 5-23-0:0~0.1.0
├── notes
│   ├── test~0.1.0
│   ├── test2~0.1.0
│   └── test3~0.1.0
└── test~0.1.0
```

I glob with `glob([ path, "/**/**"].join(""))` or  `glob([ path, "/**"].join(""))`  where `path = "/tmp/store/diary"` - but it only yields `testdiary` and `2016`, nothing below.

**Comment by blaenk** [comment]
As mentioned in the [documentation](https://doc.rust-lang.org/glob/glob/struct.Pattern.html), `**` matches recursive subdirectories. If you want to also access the files then you need a final `/*`. So `/**/*` should cover it.

Also, IIRC consecutive `/**`, e.g. `/**/**`, is redundant and treated as a single `/**`.

**Comment by JohnTitor** [comment]
Closing in favor of https://github.com/rust-lang/glob/issues/52#issuecomment-221094208
