### ISSUE TITLE
Unable to use glob / docs incomplete

### ISSUE THREAD

**Issue by mabushey** [rust-lang/glob#77]
```
~/rust/src$ cat ../Cargo.toml
[dependencies]
glob = "0.3.0"
```
```
~/rust/src$ cat main.rs
extern crate glob;

use glob::glob;

fn main() {
  for entry in glob("/media/**/*.jpg").expect("Failed to read glob pattern") {
    match entry {
      Ok(path) => println!("{:?}", path.display()),
      Err(e) => println!("{:?}", e),
    }
  }
}
```
```
~/rust/src$ rustc main.rs
error[E0463]: can't find crate for `glob`
 --> main.rs:1:1
  |
1 | extern crate glob;
  | ^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
```

I'm extremely new to rust, so I'm sure it's something basic the docs are assuming I know.

**Comment by mabushey** [comment]
I've been compiling with `rustc file.rs`. Now I have to compile with `cargo build`. Why is something so absolutely non obvious skipped? Do I have some missing config setting to make `rustc` work right?

**Comment by BurntSushi** [comment]
You probably want to start with the book, which will introduce you to Cargo: https://doc.rust-lang.org/book/index.html

**Comment by JohnTitor** [comment]
Closing as there's no update and I assume it was resolved. Feel free to add a comment if you still have any issues!
