### ISSUE TITLE
Excessive stat syscalls on linux

### ISSUE THREAD

**Issue by the8472** [rust-lang/glob#79]
The directory traversal performs a `.metadata()` on each entry to check whether it is a directory, which results in a syscall. This is extremely wasteful since `DirEntry::file_type` can grab the file type directly from the readdir results which are obtained in batches via `getdents` syscall, i.e. only 1 syscall every N directory entries.

An additional problem is that there are multiple `metadata()` calls. They are not cached on the file descriptor, so each call results in an additional syscall.

**Comment by NilsIrl** [comment]
Maybe this could also be fixed by improving the standard library? As it stands, I don't think there's anyway to access the results of `readdir` in rust (using the standard library). So I think this is more of a problem to do with the standard library.

**Comment by the8472** [comment]
> I don't think there's anyway to access the results of readdir in rust (using the standard library). 

There is, I explicitly mentioned it in my initial comment

> his is extremely wasteful since DirEntry::file_type can grab the file type directly from the readdir results
