### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/glob#89]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You most likely won't be able to transfer your repository directly, if so you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by KodrAus** [comment]
There have been plans to try rework this project for a while, but we haven't had the time to do that yet, and will probably want to keep this crate name, so migrating into `rust-lang` seems like the most appropriate move right now.

**Comment by billsb-aurizon** [comment]
@KodrAus  Just curious, why this was never moved to rust-lang?

**Comment by atouchet** [comment]
This appears to be done now.
